version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/prod/web/Dockerfile
    command: gunicorn src.wsgi:application --bind 0.0.0.0:8000
    platform: linux/amd64
    volumes:
#      - ./web/:/home/app/web
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - docker/prod/env/.staging.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - docker/prod/env/.db.staging.env
  nginx-proxy:
    container_name: nginx-proxy
    platform: linux/amd64
    build:
      context: .
      dockerfile: docker/prod/nginx/staging/Dockerfile
    image: 886317372170.dkr.ecr.us-east-1.amazonaws.com/amazing-django-ec2:nginx-proxy
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - docker/prod/env/.staging.proxy-companion.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379"
  web-uvicorn:
    build:
      context: .
      dockerfile: docker/prod/web/Dockerfile
    command: uvicorn src.asgi:application
    platform: linux/amd64
    volumes:
      #      - ./web/:/home/app/web
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - docker/prod/env/.staging.env
    depends_on:
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme:
