# Generated by Django 3.2.11 on 2023-04-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='loaders_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество грузчиков'),
        ),
    ]
