# Generated by Django 3.2.11 on 2023-04-30 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_account_avatar'),
        ('main', '0002_statement_loaders_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_added_by_account', to='auth_app.account', verbose_name='Добавил аккаунт')),
                ('favorite_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_favorite_account', to='auth_app.account', verbose_name='Избранный аккаунт')),
            ],
            options={
                'verbose_name': 'Избранный',
                'verbose_name_plural': 'Избранные',
            },
        ),
    ]
