# Generated by Django 3.2.11 on 2023-04-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_favourites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourites',
            options={'verbose_name': 'Избранный аккаунт', 'verbose_name_plural': 'Избранные аккаунты'},
        ),
    ]
