# Generated by Django 3.2.11 on 2023-05-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_favourites_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourites',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='favourites',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
