# Generated by Django 3.2.11 on 2023-05-09 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_auto_20230430_0649'),
        ('main', '0006_auto_20230509_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements', to='auth_app.account', verbose_name='Исполнитель'),
        ),
    ]
