# Generated by Django 3.2.11 on 2023-05-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_statement_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
