# Generated by Django 3.2.11 on 2023-05-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_response_price'),
        ('main', '0008_auto_20230520_1850'),
    ]

    operations = [
    ]
